esphome:
  name: immersion

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Immersion Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

output:
  - platform: ac_dimmer
    id: dimmer1
    min_power: 0.01
    gate_pin: D7
    zero_cross_pin:
      number: D6
      mode:
        input: true
      inverted: yes

fan:
  - platform: speed
    output: dimmer1
    name: Immersion Heater

    
external_components:
  # use ac_dimmer from personal dev branch in GitHub
  - source:
      type: git
      url: https://github.com/josephdouce/esphome
      ref: dev
    components: [ac_dimmer]
    refresh: 0s
