alias: Immersion Power Controller
description: ''
trigger:
  - platform: time_pattern
    seconds: /10
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.grid_import_power
            above: '75'
            below: '400'
        sequence:
          - service: fan.decrease_speed
            data:
              percentage_step: 1
            target:
              entity_id: fan.immersion_heater
      - conditions:
          - condition: numeric_state
            entity_id: sensor.grid_import_power
            above: '400'
            below: '1501'
        sequence:
          - service: fan.decrease_speed
            data:
              percentage_step: 5
            target:
              entity_id: fan.immersion_heater
      - conditions:
          - condition: numeric_state
            entity_id: sensor.grid_import_power
            above: '1500'
        sequence:
          - service: fan.decrease_speed
            data:
              percentage_step: 25
            target:
              entity_id: fan.immersion_heater
      - conditions:
          - condition: numeric_state
            entity_id: sensor.grid_export_power
            above: '75'
            below: '400'
        sequence:
          - service: fan.increase_speed
            data:
              percentage_step: 1
            target:
              entity_id: fan.immersion_heater
      - conditions:
          - condition: numeric_state
            entity_id: sensor.grid_export_power
            above: '400'
            below: '1500'
        sequence:
          - service: fan.increase_speed
            data:
              percentage_step: 5
            target:
              entity_id: fan.immersion_heater
      - conditions:
          - condition: numeric_state
            entity_id: sensor.grid_export_power
            above: '1500'
        sequence:
          - service: fan.increase_speed
            data:
              percentage_step: 25
            target:
              entity_id: fan.immersion_heater
    default: []
mode: single
